#sudo: false
sudo: required
dist: trusty

language: generic

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install texlive-latex-base texlive-latex-extra latex-beamer

install:
  # beamer
  - export TEXMFLOCAL=/tmp/texmf/ && mkdir -p $TEXMFLOCAL/tex/latex/
  # move the theme into TEXMFLOCAL
  - cp -ar * $TEXMFLOCAL/tex/latex/
  - texhash

# run test
script:
  - cd doc/example/
  - make
